### ISSUE TITLE
use tailwind jit mode

### ISSUE THREAD

**Issue by sw-yx** [one-aalam/svelte-starter-kit#15]
it eliminates having to use the class extractor and is just much faster :)

**Comment by one-aalam** [comment]
Sure 👍  Thank for wonderful suggestions!

It's a part of the `package.json` already https://github.com/one-aalam/svelte-starter-kit/blob/auth-supabase/package.json#L20. I somehow missed applying it :-)

**Comment by one-aalam** [comment]
@sw-yx I think it should work already https://github.com/one-aalam/svelte-starter-kit/blob/auth-supabase/postcss.config.cjs#L1 . Let me know if it's non-functional for you.

**Comment by sw-yx** [comment]
i dont know but should work :)

**Comment by philip-weber** [comment]
Hi @one-aalam, I'm not sure about the class extractor stuff but as I understand, the `@tailwindcss/jit` package is not being developed anymore. Instead the Tailwind team moved it into the `tailwindcss` package as of `tailwindcss@2.1`. See the corresponding blog post https://blog.tailwindcss.com/tailwindcss-2-1.
> If you were using @tailwindcss/jit before, you can now migrate to Tailwind CSS v2.1 instead, as that's where all new development on the engine will happen.

If one wants to benefit from future JIT features/bugfixes, one has to migrate

As I understand the postcss.config.cjs needs to be adapted to:
```
// postcss.config.cjs
const tailwindcss = require("tailwindcss");
// ...
```

And the tailwindcss.config.cjs needs to be adapted to:
```
// tailwind.config.cjs
module.exports = {
  mode: 'jit',
  purge: [
    // ...
  ],
  // ...
}
```


Besides that, thank you for the great starter!

**Comment by one-aalam** [comment]
Thank you, @philip-weber

Looks like I missed the updates. I was under the assumption that it still works that way. I read in one of Adam's posts that this was in roadmap, but didn't expect that it will arrive this quick :-) 

I'll do the updates in a day or two. Thanks for the pointers, and I'm glad that you liked it.

**Comment by one-aalam** [comment]
Done! @philip-weber
