### ISSUE TITLE
Login with magic link does not set cookie

### ISSUE THREAD

**Issue by aslak01** [one-aalam/svelte-starter-kit#17]
I've set up this project, and if I log in with only email it does not unflag `guest: true`. Only if I use username and password it takes me to the profile page. Also, the link to `/profile` is written as `/profile@me` which returns a 404.

**Comment by one-aalam** [comment]
Sure @aslak01 Thanks for bringing it to my notice. I'll have a look.

**Comment by one-aalam** [comment]
The issue is fixed now @aslak01. Thank you for bringing it to my notice.
