### ISSUE TITLE
Determining which pages can be accessed

### ISSUE THREAD

**Issue by Chris-Mingay** [one-aalam/svelte-starter-kit#18]
Hi there, just starting out with Svelte and Supabase and really appreciate your efforts with this project.

I'm wondering if you can point me in the direction of the code in this project that prevents access to `/profile` when the user is not logged in (it automatically redirects to `/`)

Thanks

**Comment by one-aalam** [comment]
Thanks @Chris-Mingay Glad you liked it!

The code that performs the redirection can be found here https://github.com/one-aalam/svelte-starter-kit/blob/43e4e9e599a0c8abfef5ef07534fe90106000f3d/src/routes/profile.svelte#L13

**Comment by Chris-Mingay** [comment]
Haha sorry that was me being stupid in the end and forgetting the whole server / client side rendering thing. I put a console.log there expecting to see something in chrome developer tools but it never showed.

Had I looked at the `npm run dev` window I would have seen it there.... woops! 

Thanks for getting back to me
