### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by haruzinh0** [one-aalam/svelte-starter-kit#23]
why you uses hooks to handle the session handshake and how important it is? should i really use the hooks? thanks

**Comment by haruzinh0** [comment]
uh? hello?

**Comment by one-aalam** [comment]
Hey @haruzinh0. Though hooks are optional, they're run every time SvelteKit receives a request on the server. This property  makes it a useful place to do request and response modification. Few details like user information are needed by almost all the protected routes, and placing the user extraction/patching logic in hooks makes the detail consistently available in all the API and page routes through `getSession`. This could've been handled a bit differently too, but I intended to centralise the Supabase (auth) interacting code on the server.

Hope, this answers your query?

**Comment by one-aalam** [comment]
closing this, as this issue intended to receive some clarity, not  a code fix.
