### ISSUE TITLE
$page.query has been replaced by $page.url.searchParams

### ISSUE THREAD

**Issue by jamespdaily** [one-aalam/svelte-starter-kit#24]
The application throws an error stating: $page.query has been replaced by $page.url.searchParams when trying out this template

**Comment by one-aalam** [comment]
Thanks for opening the issue @jamespdaily. As the per the latest SvelteKit updates there's good amount of updates this repo might receive. I hope and look forward  to resolve all the open issues as per the latest SvelteKit update in next sitting, most definitely in a week's time.
